# Separating this for ease of visualization
- type: vessel
  id: BaseVessel
  abstract: true
  name: AAA Bikeshed
  description: Questionably spaceworthy.
  price: 50000
  category: Medium
  group: Shipyard
  addComponents:
  - type: IFF
    color: '#FFFFFFFF'
    flags: [IsPlayerShuttle]

- type: vessel
  id: BaseVesselNfsd
  parent: BaseVessel
  abstract: true
  addComponents:
  - type: GridAccess
    tags: [ NFSD ]

- type: vessel
  id: BaseVesselAntag
  parent: BaseVessel
  abstract: true
  addComponents:
  - type: IFF
    flags: [IsPlayerShuttle, HideLabel]

- type: vessel
  id: BaseVesselPirate
  parent: BaseVesselAntag
  abstract: true
  addComponents:
  - type: GridAccess
    tags: [ Pirate ]