using Content.Shared._NF.CartridgeLoader.Cartridges;
using Content.Shared.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._NF.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class LedgerStatsUiFragment : BoxContainer
{

    public LedgerStatsUiFragment()
    {
        RobustXamlLoader.Load(this);

        // This my way of adding multiple classes to a XAML control.
        OpenedMailCount.StyleClasses.Add("Good");
        OpenedMailSpesos.StyleClasses.Add("Good");
        TamperedMailCount.StyleClasses.Add("Danger");
        TamperedMailSpesos.StyleClasses.Add("Danger");
        ExpiredMailCount.StyleClasses.Add("Danger");
        ExpiredMailSpesos.StyleClasses.Add("Danger");
        DamagedMailCount.StyleClasses.Add("Danger");
        DamagedMailSpesos.StyleClasses.Add("Danger");
        UnopenedMailCount.StyleClasses.Add("Caution");
    }

    public void UpdateState(LedgerStatsUiState state)
    {
        UpdateTextLabels(state);
        UpdateSuccessGrade(state);
    }

    public void UpdateTextLabels(LedgerStatsUiState state)
    {
        var stats = state.Stats;

        OpenedMailCount.Text = stats.OpenedCount.ToString();
        OpenedMailSpesos.Text = stats.Earnings.ToString();
        TamperedMailCount.Text = stats.TamperedCount.ToString();
        TamperedMailSpesos.Text = stats.TamperedLosses.ToString();
        ExpiredMailCount.Text = stats.ExpiredCount.ToString();
        ExpiredMailSpesos.Text = stats.ExpiredLosses.ToString();
        DamagedMailCount.Text = stats.DamagedCount.ToString();
        DamagedMailSpesos.Text = stats.DamagedLosses.ToString();
        UnopenedMailCount.Text = state.UnopenedMailCount.ToString();
        TotalMailCount.Text = state.TotalMail.ToString();
        TotalMailSpesos.Text = stats.TotalIncome.ToString();
        SuccessRateCounts.Text = Loc.GetString("mail-metrics-progress",
            ("opened", stats.OpenedCount),
            ("total", state.TotalMail));
        SuccessRatePercent.Text = Loc.GetString("mail-metrics-progress-percent",
            ("successRate", state.SuccessRate));
    }
}
